-- THRIVE FIRST PARTICIPANT BUDGET PERIOD CONTROLLED INSTALL v0.3
-- APPROVED CONTROLLED SYNTHETIC INSTALL
-- EXECUTE ONCE AS THE FIXTURE WORKSPACE ADMIN

begin;

-- Controlled synthetic fixture
-- Workspace: 71000000-0000-4000-8000-000000000001
-- Program:   71000000-0000-4000-8000-000000000002
-- Person D:  71000000-0000-4000-8000-000000000009
--
-- Candidate period: February 2099
-- Synthetic planning data only.

do $$
begin
  if auth.uid() is null then
    raise exception 'Authenticated workspace admin context is required';
  end if;

  if not public.is_workspace_admin(
    '71000000-0000-4000-8000-000000000001'::uuid
  ) then
    raise exception 'Authenticated user is not an active fixture workspace admin';
  end if;

  if not exists (
    select 1
    from public.program_participants pp
    where pp.workspace_id =
      '71000000-0000-4000-8000-000000000001'::uuid
      and pp.program_id =
        '71000000-0000-4000-8000-000000000002'::uuid
      and pp.supported_person_id =
        '71000000-0000-4000-8000-000000000009'::uuid
      and pp.status = 'active'
  ) then
    raise exception 'Person D active fixture participation is missing';
  end if;

  if exists (
    select 1
    from public.participant_budget_periods
    where id = '73000000-0000-4000-8000-000000000001'::uuid
  ) then
    raise exception 'Synthetic budget period ID already exists';
  end if;

  if exists (
    select 1
    from public.participant_budget_periods
    where supported_person_id =
      '71000000-0000-4000-8000-000000000009'::uuid
      and period_start = date '2099-02-01'
      and period_end = date '2099-02-28'
      and status = 'active'
  ) then
    raise exception 'An active exact February 2099 budget period already exists';
  end if;
end;
$$;

insert into public.participant_budget_periods (
  id,
  workspace_id,
  program_id,
  supported_person_id,
  period_start,
  period_end,
  status,
  expected_income,
  notes,
  created_by
)
values (
  '73000000-0000-4000-8000-000000000001'::uuid,
  '71000000-0000-4000-8000-000000000001'::uuid,
  '71000000-0000-4000-8000-000000000002'::uuid,
  '71000000-0000-4000-8000-000000000009'::uuid,
  date '2099-02-01',
  date '2099-02-28',
  'active',
  2400.00,
  'Synthetic participant Budget period for authenticated read validation only.',
  auth.uid()
);

-- remaining_amount is generated by the live database.
insert into public.participant_budget_lines (
  id,
  budget_period_id,
  category_name,
  category_type,
  planned_amount,
  actual_amount,
  sort_order,
  is_active
)
values
(
  '73000000-0000-4000-8000-000000000011'::uuid,
  '73000000-0000-4000-8000-000000000001'::uuid,
  'Housing and utilities',
  'protected',
  1400.00,
  0.00,
  10,
  true
),
(
  '73000000-0000-4000-8000-000000000012'::uuid,
  '73000000-0000-4000-8000-000000000001'::uuid,
  'Food and household',
  'protected',
  500.00,
  25.00,
  20,
  true
),
(
  '73000000-0000-4000-8000-000000000013'::uuid,
  '73000000-0000-4000-8000-000000000001'::uuid,
  'Transportation',
  'flexible',
  200.00,
  10.00,
  30,
  true
),
(
  '73000000-0000-4000-8000-000000000014'::uuid,
  '73000000-0000-4000-8000-000000000001'::uuid,
  'Reserve',
  'reserve',
  300.00,
  0.00,
  40,
  true
);

select
  p.id as budget_period_id,
  p.status,
  p.expected_income,
  count(l.id) as line_count,
  coalesce(sum(l.planned_amount), 0) as total_planned_amount,
  coalesce(sum(l.actual_amount), 0) as total_actual_amount,
  coalesce(sum(l.remaining_amount), 0) as total_remaining_amount
from public.participant_budget_periods p
left join public.participant_budget_lines l
  on l.budget_period_id = p.id
where p.id = '73000000-0000-4000-8000-000000000001'::uuid
group by p.id, p.status, p.expected_income;

select
  category_name,
  category_type,
  planned_amount,
  actual_amount,
  remaining_amount,
  sort_order,
  is_active
from public.participant_budget_lines
where budget_period_id =
  '73000000-0000-4000-8000-000000000001'::uuid
order by sort_order;

commit;
